---
Gemfile:
  required:
    ':dependencies':
      - gem: xml-simple
    ':development':
      - gem: pdk
'spec/spec_helper.rb':
  mock_with: ':rspec'
  spec_overrides: >-
    RSpec.configure do |c|
      c.after(:suite) do
        RSpec::Puppet::Coverage.report!
      end
    end
.travis.yml:
  user: innogames
  secure: "YsTvDpCHiuMpQ41X5GMUz8kbbHUAXVVoUWsnzXdsq5UnSMgVVTrQTnrzRSwFSKtkQJkm+N5BOn1WXj3te+eGsV+Ca4hXk/hygKcHMZNBT3ZKJs1GJdW4CfOxBzdgHjT7cY7UFaDFB1vb8S6dC36R03kqizVuiWI3KC9cO5msgPB5LSIxnJYDkRqZcHPQFF8EAgIP/zidlt18fYhbTOcG61vN59aGcl3aYHxD8YGgKe5OOQk41GxvWe6tsFFHW9f8Bg7FwwMLfA7sii4TV3tW9XXP9WhfL+/VhazIPf8cLK017W4RaHi3NW+GT9d3fz15UWYta7/69i8fzg+1w+0y7hA4Fm2+aunuArYvKIzf+3erBa8RvJE563wP3xx20czjsmP26ecTo0uyHiqvovhHUF7s39EWyQgv6zNPOT5IfYKDTZxj/wMIYUEas9GPJOYjyPi08TkIK2ABi2SQsPeXz7gTaANaTeIR8jcvxNItZ9Kr0SkazZaRMUJI3Lhn1dx2jt705H5FdjFFC2xLfVdFgJVNHUTuO9ZWEH73QJnj6g11lwFDejz8xAdcpi287kpOQ59rVit8Tn2y+CJY9R30o1ac5CKQ6EXpP7DuZRiPx7+S4OQItwX7ep5GiOgo6mD5VsaPr3uHebT9islxzvCboIFv+FcPkmrTwFI0fJQFY5A="
  stages:
    - test
